###配置数据源信息
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.0.103:3306/jdbc
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mapper/*.xml



logging:
  level:
    com.lucifer.springboot.cache.mapper: debug
